language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode

before_script: "sudo ntpdate -ub ntp.ubuntu.com pool.ntp.org; true"
script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: rbx-19mode